// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistema.Models;

namespace sistema.Migrations
{
    [DbContext(typeof(SistemaContext))]
    [Migration("20181120090647_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("sistema.Models.AccessToken", b =>
                {
                    b.Property<int>("IdAccessToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<byte[]>("AccessToken1")
                        .IsRequired()
                        .HasColumnName("AccessToken")
                        .HasColumnType("blob");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("date");

                    b.Property<int>("Origem")
                        .HasColumnType("int(11)");

                    b.Property<int>("PessoaFisica")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("date");

                    b.HasKey("IdAccessToken");

                    b.HasIndex("Origem")
                        .HasName("FK_ea_idx");

                    b.HasIndex("PessoaFisica")
                        .HasName("FK_pf_idx");

                    b.ToTable("AccessToken","Sistema");
                });

            modelBuilder.Entity("sistema.Models.EntidadeAutenticadora", b =>
                {
                    b.Property<int>("IdEntidadeAutenticadora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false);

                    b.HasKey("IdEntidadeAutenticadora");

                    b.ToTable("EntidadeAutenticadora","Sistema");
                });

            modelBuilder.Entity("sistema.Models.PessoaFisica", b =>
                {
                    b.Property<int>("IdPessoaFisica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<byte?>("Maior")
                        .HasColumnType("tinyint(4)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("date");

                    b.Property<string>("NickName")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(false);

                    b.HasKey("IdPessoaFisica");

                    b.ToTable("PessoaFisica","Sistema");
                });

            modelBuilder.Entity("sistema.Models.AccessToken", b =>
                {
                    b.HasOne("sistema.Models.EntidadeAutenticadora", "OrigemNavigation")
                        .WithMany("AccessToken")
                        .HasForeignKey("Origem")
                        .HasConstraintName("FK_ea");

                    b.HasOne("sistema.Models.PessoaFisica", "PessoaFisicaNavigation")
                        .WithMany("AccessToken")
                        .HasForeignKey("PessoaFisica")
                        .HasConstraintName("FK_pf");
                });
#pragma warning restore 612, 618
        }
    }
}
